### ISSUE TITLE
When CG isn't found compile errors

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-uig#1]
```
make: *** No rule to make target `no', needed by `uig.rlx.bin'.  Stop.
```

The "no" comes from the `$(CGCOMP)` variable in the `Makefile`. The Makefile should probably not try and compile the CG if it is not there.

This probably applies to other languages too.

**Comment by ftyers** [comment]
In 4c56906 I added some stuff to the `configure.ac` and the `Makefile.am` but I think that they do the wrong thing. Needs to be checked.

**Comment by MemduhG** [comment]
can we add the rlx to the targets so `make` complies it by default?

**Comment by ftyers** [comment]
I think it now works from 676fb06, please check and close the issue if it works for you @MemduhG

**Comment by MemduhG** [comment]
yep it's working for me, thanks @ftyers
