### ISSUE TITLE
Clitics not splitting off

### ISSUE THREAD

**Issue by MemduhG** [apertium/apertium-uig#6]
```
LEXICON CLITICS
# ;
%<qst%>:%>ﻡۇ V-COP-PERS ;
%<qst%>:%>چۇ # ;
!!%<gm%>:%>%{D%}ۇﺭ # ;
%<comp%>:%>ﺭ%{A%}%{K%} # ;
%<dek%>:%>%{D%}ەﻙ # ;
%<che%>:%>چە # ;
%<dub%>:%>%{y%}ﻙەﻥ V-COP-PERS ;
%<postadv%>:%>مۇ # ;
%<cnjadv%>:%>كى # ; !
```

It looks like these clitics are not splitting off properly, causing their tags to be added to the previous word, e.g.
`^سىرت<n><px3sp><loc><p3><sg><cnjadv>$`
The solution is to split them off and make sure they are assigned their own lemmas:
`+%+كى%<cnjadv%>:%>كى # ; !`

**Comment by MemduhG** [comment]
Changes in transfer will probably have to be made to accomodate the changes made here.

**Comment by ftyers** [comment]
Usually the `.t4x` file is used for rejoining clitics to their previous word.

**Comment by koguzhan** [comment]
`%<comp%>:%>ﺭ%{A%}%{K%} # ;
%<dek%>:%>%{D%}ەﻙ # ;
%<che%>:%>چە # ;
%<dub%>:%>%{y%}ﻙەﻥ V-COP-PERS ;`
should be working fine so maybe we should write similar rules for the other ones as well? Unless you want these to appear split in the analysis I mean.

**Comment by MemduhG** [comment]
I think Fran made the changes required, if you could git pull check that would be nice because I'm at work :/

**Comment by MemduhG** [comment]
I think this issue is sorted out
